//HTML to be generated by javascript upon calling function in index.js//

// use const variables from index.js as template literals to fill in dynamic info //

function htmltoGenerate(res){
    return `<html>
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    </head>
    <body>
        <div class="jumbotron jumbotron-fluid">
            <div class="container">
                <img src=${res.data.avatar_url}/>
                <h1 class="display-4">Hi</h1>
                <p>My name is ${res.data.name}</p>
                <ul class="list-group list-group-horizontal">
                    <li class="list-group-item">Location: <a href="https://www.google.com/maps/place/${res.data.location}">${res.data.location}</a></li>
                    <li class="list-group-item"><a href=${res.data.repos_url}>GitHub Repo</a></li>
                    <li class="list-group-item"><a href=${res.data.blog}>Blog</a></li>
                </ul>
            </div>
          </div>
          <div class="container">
        <div class="row">
                <div class="col-10">
                    <h2>${res.data.bio}</h2>
                </div>
        </div>  
        <div class="row">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                  <h5 class="card-title">Public Repositories</h5>
                  <h6 class="card-subtitle mb-2 text-muted">${res.data.public_repos}</h6>
                </div>
              </div>
              <div class="col-2"></div>
              <div class="card" style="width: 18rem;">
                <div class="card-body">
                  <h5 class="card-title">Followers</h5>
                  <h6 class="card-subtitle mb-2 text-muted">${res.data.followers}</h6>
                </div>
              </div>
        </div>
        <div class="row"><p></p></div>
        <div class="row">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                  <h5 class="card-title">GitHub Stars</h5>
                  <h6 class="card-subtitle mb-2 text-muted"></h6>
                </div>
              </div>
              <div class="col-2"></div>
              <div class="card" style="width: 18rem;">
                <div class="card-body">
                  <h5 class="card-title">Following</h5>
                  <h6 class="card-subtitle mb-2 text-muted">${res.data.following}</h6>
                </div>
              </div>
        </div>
        </div>
            
          </div>
    </body>
</html>`
}

//export this function as a module to use in index.js

module.exports = htmltoGenerate